apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hue
  namespace: '{{ "NAMESPACE" | env }}'
data:
  sentry-dsn: '{{ "SENTRY_DSN_KEY" | env | teamvaultUrl | base64 }}'
  token: '{{ "TOKEN_KEY" | env | teamvaultPassword | base64 }}'
