apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hue
  namespace: '{{ "NAMESPACE" | env }}'
spec:
  ingressClassName: 'traefik'
  rules:
    - host: 'hue.hell.hm.benjamin-borbe.de'
      http:
        paths:
          - backend:
              service:
                name: hue
                port:
                  name: http
            path: /
            pathType: Prefix
