// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/amimof/huego"
	"github.com/bborbe/hue/pkg"
)

type BridgesProvider struct {
	GetBridgesStub        func(context.Context) ([]*huego.Bridge, error)
	getBridgesMutex       sync.RWMutex
	getBridgesArgsForCall []struct {
		arg1 context.Context
	}
	getBridgesReturns struct {
		result1 []*huego.Bridge
		result2 error
	}
	getBridgesReturnsOnCall map[int]struct {
		result1 []*huego.Bridge
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *BridgesProvider) GetBridges(arg1 context.Context) ([]*huego.Bridge, error) {
	fake.getBridgesMutex.Lock()
	ret, specificReturn := fake.getBridgesReturnsOnCall[len(fake.getBridgesArgsForCall)]
	fake.getBridgesArgsForCall = append(fake.getBridgesArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetBridgesStub
	fakeReturns := fake.getBridgesReturns
	fake.recordInvocation("GetBridges", []interface{}{arg1})
	fake.getBridgesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *BridgesProvider) GetBridgesCallCount() int {
	fake.getBridgesMutex.RLock()
	defer fake.getBridgesMutex.RUnlock()
	return len(fake.getBridgesArgsForCall)
}

func (fake *BridgesProvider) GetBridgesCalls(stub func(context.Context) ([]*huego.Bridge, error)) {
	fake.getBridgesMutex.Lock()
	defer fake.getBridgesMutex.Unlock()
	fake.GetBridgesStub = stub
}

func (fake *BridgesProvider) GetBridgesArgsForCall(i int) context.Context {
	fake.getBridgesMutex.RLock()
	defer fake.getBridgesMutex.RUnlock()
	argsForCall := fake.getBridgesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *BridgesProvider) GetBridgesReturns(result1 []*huego.Bridge, result2 error) {
	fake.getBridgesMutex.Lock()
	defer fake.getBridgesMutex.Unlock()
	fake.GetBridgesStub = nil
	fake.getBridgesReturns = struct {
		result1 []*huego.Bridge
		result2 error
	}{result1, result2}
}

func (fake *BridgesProvider) GetBridgesReturnsOnCall(i int, result1 []*huego.Bridge, result2 error) {
	fake.getBridgesMutex.Lock()
	defer fake.getBridgesMutex.Unlock()
	fake.GetBridgesStub = nil
	if fake.getBridgesReturnsOnCall == nil {
		fake.getBridgesReturnsOnCall = make(map[int]struct {
			result1 []*huego.Bridge
			result2 error
		})
	}
	fake.getBridgesReturnsOnCall[i] = struct {
		result1 []*huego.Bridge
		result2 error
	}{result1, result2}
}

func (fake *BridgesProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *BridgesProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.BridgesProvider = new(BridgesProvider)
