// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/hue/pkg/check"
)

type CheckCreator struct {
	CreateChecksStub        func(context.Context) (check.CheckList, error)
	createChecksMutex       sync.RWMutex
	createChecksArgsForCall []struct {
		arg1 context.Context
	}
	createChecksReturns struct {
		result1 check.CheckList
		result2 error
	}
	createChecksReturnsOnCall map[int]struct {
		result1 check.CheckList
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CheckCreator) CreateChecks(arg1 context.Context) (check.CheckList, error) {
	fake.createChecksMutex.Lock()
	ret, specificReturn := fake.createChecksReturnsOnCall[len(fake.createChecksArgsForCall)]
	fake.createChecksArgsForCall = append(fake.createChecksArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.CreateChecksStub
	fakeReturns := fake.createChecksReturns
	fake.recordInvocation("CreateChecks", []interface{}{arg1})
	fake.createChecksMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *CheckCreator) CreateChecksCallCount() int {
	fake.createChecksMutex.RLock()
	defer fake.createChecksMutex.RUnlock()
	return len(fake.createChecksArgsForCall)
}

func (fake *CheckCreator) CreateChecksCalls(stub func(context.Context) (check.CheckList, error)) {
	fake.createChecksMutex.Lock()
	defer fake.createChecksMutex.Unlock()
	fake.CreateChecksStub = stub
}

func (fake *CheckCreator) CreateChecksArgsForCall(i int) context.Context {
	fake.createChecksMutex.RLock()
	defer fake.createChecksMutex.RUnlock()
	argsForCall := fake.createChecksArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CheckCreator) CreateChecksReturns(result1 check.CheckList, result2 error) {
	fake.createChecksMutex.Lock()
	defer fake.createChecksMutex.Unlock()
	fake.CreateChecksStub = nil
	fake.createChecksReturns = struct {
		result1 check.CheckList
		result2 error
	}{result1, result2}
}

func (fake *CheckCreator) CreateChecksReturnsOnCall(i int, result1 check.CheckList, result2 error) {
	fake.createChecksMutex.Lock()
	defer fake.createChecksMutex.Unlock()
	fake.CreateChecksStub = nil
	if fake.createChecksReturnsOnCall == nil {
		fake.createChecksReturnsOnCall = make(map[int]struct {
			result1 check.CheckList
			result2 error
		})
	}
	fake.createChecksReturnsOnCall[i] = struct {
		result1 check.CheckList
		result2 error
	}{result1, result2}
}

func (fake *CheckCreator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CheckCreator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ check.CheckCreator = new(CheckCreator)
