// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/hue/pkg/check"
)

type ChecksRunner struct {
	RunChecksStub        func(context.Context, check.Checks) error
	runChecksMutex       sync.RWMutex
	runChecksArgsForCall []struct {
		arg1 context.Context
		arg2 check.Checks
	}
	runChecksReturns struct {
		result1 error
	}
	runChecksReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ChecksRunner) RunChecks(arg1 context.Context, arg2 check.Checks) error {
	fake.runChecksMutex.Lock()
	ret, specificReturn := fake.runChecksReturnsOnCall[len(fake.runChecksArgsForCall)]
	fake.runChecksArgsForCall = append(fake.runChecksArgsForCall, struct {
		arg1 context.Context
		arg2 check.Checks
	}{arg1, arg2})
	stub := fake.RunChecksStub
	fakeReturns := fake.runChecksReturns
	fake.recordInvocation("RunChecks", []interface{}{arg1, arg2})
	fake.runChecksMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ChecksRunner) RunChecksCallCount() int {
	fake.runChecksMutex.RLock()
	defer fake.runChecksMutex.RUnlock()
	return len(fake.runChecksArgsForCall)
}

func (fake *ChecksRunner) RunChecksCalls(stub func(context.Context, check.Checks) error) {
	fake.runChecksMutex.Lock()
	defer fake.runChecksMutex.Unlock()
	fake.RunChecksStub = stub
}

func (fake *ChecksRunner) RunChecksArgsForCall(i int) (context.Context, check.Checks) {
	fake.runChecksMutex.RLock()
	defer fake.runChecksMutex.RUnlock()
	argsForCall := fake.runChecksArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ChecksRunner) RunChecksReturns(result1 error) {
	fake.runChecksMutex.Lock()
	defer fake.runChecksMutex.Unlock()
	fake.RunChecksStub = nil
	fake.runChecksReturns = struct {
		result1 error
	}{result1}
}

func (fake *ChecksRunner) RunChecksReturnsOnCall(i int, result1 error) {
	fake.runChecksMutex.Lock()
	defer fake.runChecksMutex.Unlock()
	fake.RunChecksStub = nil
	if fake.runChecksReturnsOnCall == nil {
		fake.runChecksReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runChecksReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ChecksRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ChecksRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ check.ChecksRunner = new(ChecksRunner)
