run:
	go run main.go \
	-url=$$(teamvault-url --teamvault-config ~/.teamvault.json --teamvault-key=QL3QQw) \
	-id=$$(teamvault-password --teamvault-config ~/.teamvault.json --teamvault-key=QL3QQw) \
	-token=$$(teamvault-password --teamvault-config ~/.teamvault.json --teamvault-key=QL3QQw) \
	-v=2
